# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('current_salary', models.CharField(max_length=50)),
                ('expected_salary', models.CharField(max_length=50)),
                ('edulevel', models.CharField(max_length=50)),
                ('uploadcv', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('aboutme', models.CharField(max_length=50)),
                ('skill_name', models.CharField(max_length=50)),
                ('skill_level', models.CharField(max_length=50)),
                ('degree_name', models.CharField(max_length=50)),
                ('degree_date', models.CharField(max_length=50)),
                ('about_degree', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('company_website', models.CharField(max_length=50)),
                ('join_from', models.CharField(max_length=50)),
                ('endon', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('about_company', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('project_start', models.CharField(max_length=50)),
                ('project_end', models.CharField(max_length=50)),
                ('project_desc', models.CharField(max_length=50)),
                ('project_file', models.CharField(blank=True, max_length=255)),
                ('project_document', models.FileField(upload_to='documents/')),
                ('project_uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facebook', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('google_plus', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('pinterest', models.CharField(max_length=50)),
                ('behance', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'PersonalInfo',
            },
        ),
    ]
