# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_candidateinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='document',
        ),
        migrations.RemoveField(
            model_name='candidateinfo',
            name='project_document',
        ),
    ]
