# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-07 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170306_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='email',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
